branches: {only: [master]}
sudo: false
dist: trusty

language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'

cache: pip

addons:
  postgresql: 9.5

install: 'pip install -r requirements.txt -r requirements-dev.txt'

before_script:
  - psql -c 'create database palautebot;' -U postgres

script:
  - pytest -ra -vvv --cov

after_success: pip install codecov && codecov

env:
  - TEST_PART=tests SECRET_KEY=topsecret123 DATABASE_URL="postgres://postgres:@localhost/palautebot"

matrix:
  include:
    - env: TEST_PART=style
      install: pip install -r requirements.txt -r requirements-dev.txt
      script:
        - flake8
        - isort -c
