# Generated by Django 2.0.2 on 2018-02-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('twitter', 'Twitter')], max_length=2048)),
                ('source_id', models.CharField(max_length=2048)),
                ('source_created_at', models.DateTimeField(db_index=True)),
                ('ticket_id', models.CharField(blank=True, db_index=True, max_length=2048)),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedback',
            },
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('source', 'source_id')},
        ),
    ]
