# Generated by Django 2.0.2 on 2018-02-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_id', models.CharField(max_length=255)),
                ('source_created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'direct message',
                'verbose_name_plural': 'direct messages',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=255, unique=True, verbose_name='ticket ID')),
                ('current_comment', models.TextField(blank=True, verbose_name='current comment')),
            ],
            options={
                'verbose_name': 'feedback item',
                'verbose_name_plural': 'feedback items',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_id', models.CharField(max_length=255)),
                ('source_created_at', models.DateTimeField(db_index=True)),
                ('user_identifier', models.CharField(blank=True, db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'tweet',
                'verbose_name_plural': 'tweets',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Tweet', verbose_name='tweet'),
        ),
    ]
