# Generated by Django 2.0.2 on 2018-02-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_identifier',
            field=models.CharField(db_index=True, blank=True, max_length=2048),
        ),
    ]
