# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palautebot', '0004_auto_20170517_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='source_type',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=2048),
        ),
    ]
