# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palautebot', '0002_remove_feedback_source_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='source_created_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
