# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palautebot', '0003_feedback_source_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='source_created_at',
            field=models.DateTimeField(default='2017-05-17T09:00:00+0000'),
        ),
    ]
